# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
  - main

pool:
  name: Default
  demands:
    - Agent.Name -equals BEALEXANDER1831

jobs:
  - job: DetectChanges
    displayName: 'Detect changes in backend and frontend'
    steps:
      - script: |
          git diff --quiet HEAD^ HEAD -- backend/ || set BACKEND_CHANGED=true
          git diff --quiet HEAD^ HEAD -- frontend/ || set FRONTEND_CHANGED=true
          echo ##vso[task.setvariable variable=BACKEND_CHANGED]%BACKEND_CHANGED%
          echo ##vso[task.setvariable variable=FRONTEND_CHANGED]%FRONTEND_CHANGED%
        displayName: 'Set change detection variables'
        
  - job: BackendBuild
    displayName: 'Build and Push Backend'
    condition: eq(variables['BACKEND_CHANGED'], 'true')
    dependsOn: DetectChanges
    steps:
    - task: Docker@2
      displayName: 'Login to ACR'
      inputs:
        command: login
        containerRegistry: 'CashflowDockerRegistry'
    
    - task: PowerShell@2
      displayName: 'Build Image'
      inputs:
        targetType: 'inline'
        script: 'docker build -t benalexandercashflowregistry.azurecr.io/cashflow-backend backend/Cashflow'
    
    - task: PowerShell@2
      displayName: 'Push Image'
      inputs:
        targetType: 'inline'
        script: 'docker push benalexandercashflowregistry.azurecr.io/cashflow-backend'
    
    - script: echo "Docker image pushed to ACR successfully!"
      displayName: 'Notify Success'

  - job: FrontendBuild
    displayName: 'Build and Deploy Frontend'
    condition: eq(variables['FRONTEND_CHANGED'], 'true')
    dependsOn: DetectChanges
    steps:
      - script: echo "Frontend build steps will go here"
        displayName: 'Placeholder for frontend tasks'
