# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  name: Default
  demands:
    - Agent.Name -equals BEALEXANDER1831
  vmImage: 'ubuntu-latest'

variables:
  acrName: 'benalexandercashflowregistry'
  imageName: 'cashflow-backend'
  dockerfilePath: 'backend/Cashflow/Dockerfile'
  buildContext: 'backend/Cashflow'

steps:
- task: Docker@2
  displayName: 'Login to ACR'
  inputs:
    command: login
    containerRegistry: 'CashflowDockerRegistry'

- task: Docker@2
  displayName: 'Build and Tag Docker Image'
  inputs:
    command: build
    repository: $(acrName).azurecr.io/$(imageName)
    dockerfile: $(dockerfilePath)
    buildContext: $(buildContext)
    tags: |
      latest
      $(Build.BuildId)

- task: PowerShell@2
  displayName: 'Push Image'
  inputs:
    targetType: 'inline'
    script: 'docker push benalexandercashflowregistry.azurecr.io/cashflow-backend'

- script: echo "Docker image pushed to ACR successfully!"
  displayName: 'Notify Success'
