# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  dockerRegistryServiceConnection: 'CashflowACRServiceConnection'
  containerRepository: 'cashflow'
  imageName: 'cashflow-backend'
  tag: '$(Build.BuildId)'
  azureWebAppName: 'cashflow-backend'
  azureSubscription: 'Azure Subscription 1'

stages:
- stage: Build
  displayName: "Build and Push Docker Image"
  jobs:
  - job: Build
    displayName: "Build and Push"
    pool:
      vmImage: "ubuntu-latest"
    steps:
    - task: Docker@2
      displayName: "Build and Push Docker Image"
      inputs:
        command: buildAndPush
        repository: $(containerRepository)/$(imageName)
        dockerfile: Dockerfile
        tags: |
          latest
          $(tag)
        containerRegistry: $(dockerRegistryServiceConnection)

- stage: Deploy
  displayName: "Deploy to Azure Web App"
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Deploy
    displayName: "Deploy to Azure"
    pool:
      vmImage: "ubuntu-latest"
    steps:
    - task: AzureWebAppContainer@1
      displayName: "Deploy to Azure Web App"
      inputs:
        azureSubscription: $(azureSubscription)
        appName: $(azureWebAppName)
        containers: |
          <YourContainerRegistryURL>/$(containerRepository)/$(imageName):$(tag)
