trigger:
  branches:
    include:
      - main
  paths:
    include:
      - frontend/*

pool:
  name: Default
  demands:
    - Agent.Name -equals BEALEXANDER1831
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: 'Login to ACR'
  inputs:
    command: login
    containerRegistry: 'CashflowDockerRegistry'

- task: PowerShell@2
  displayName: 'Build Image'
  inputs:
    targetType: 'inline'
    script: 'docker build -t benalexandercashflowregistry.azurecr.io/cashflow-frontend frontend/cashflow'

- task: PowerShell@2
  displayName: 'Push Image'
  inputs:
    targetType: 'inline'
    script: 'docker push benalexandercashflowregistry.azurecr.io/cashflow-frontend'

- script: echo "Docker image pushed to ACR successfully!"
  displayName: 'Notify Success'